### ISSUE TITLE
How can I use other 2D Live model?

### ISSUE THREAD

**Issue by Kabinia1001** [AIVTDevPKevin/AI-VTuber-System#1]
Hello PKevin. 
I managed to build an AI after watching your video tutorial. But I have a small problem, other models don't move and lip sync except for the model shown in the video. How can I move other models as well?

**Comment by AIVTDevPKevin** [comment]
In the Model Settings.
![image](https://github.com/user-attachments/assets/13538a38-0d0d-4705-9ff5-a336cb57e81f)
If it's your first time using the model, VTS will probably ask if you want it to automatically set up the parameters for you.

Look for the "Mouth Open" parameter below. If it's not there, just create one.
![image](https://github.com/user-attachments/assets/270bf400-5327-41b0-a240-43788b0fa125)
Choose "VoiceVolumePlusMouthOpen" for Input and "ParamMouthOpenY" for Output.
The Output parameter name might be different depending on how the model names its parameters.
Hope this helps solve your problem.😇

**Comment by Kabinia1001** [comment]
It works! Thank you so much!
