### ISSUE TITLE
Editing UI error

### ISSUE THREAD

**Issue by norimudo** [AIVTDevPKevin/AI-VTuber-System#2]
I tried to slightly modify the application UI for myself, so that it would be easier to position the buttons. I open the .ui file in QtDesign, edit it, and then recompile it into a .py file. However, trying to run the application produces a syntax error. I've tried changing the Qt version, I've even tried just exporting the same .ui file without changes and recompiling it, but I still get the error. Where am I going wrong and how can I make changes without getting these errors. Pls help.

**Comment by AIVTDevPKevin** [comment]
That does seem a bit strange. I tried the latest v1.3 (All-in-One) version with its .ui file, and it worked fine.

Maybe you can try my Python environment. It's made with Anaconda.
https://drive.google.com/file/d/1lvN2J8PxrZKJqMT4H4PpLJNXcQG-DXwb/view?usp=sharing

After extracting, place the "AIVTuberSystem_03" folder in the following path:
```
C:\Users\YOUR USER NAME\anaconda3\envs
```

Then open CMD.exe Prompt in Anaconda.
![image](https://github.com/user-attachments/assets/42b8b8d0-551e-482b-ac02-27e8da37d53a)
Set the working directory to the folder containing the .ui file with the following command:
```
cd C:\YOUR PATH\AI-VTuber-System_ver1.3\GUI_control_panel\GUI_py
```

Enter the command to convert the .ui file to .py:
```
pyside6-uic -o AI_Vtuber_control_panel_ui_pysd6.py AI_Vtuber_control_panel_ui_pysd6.ui
```

Hope this will help. 😇

**Comment by norimudo** [comment]
I realized that it wasn't the .ui to .py compiler that was the problem, but the way QtCreator opens and then exports your .ui file. Apparently there is a compatibility problem. Where did you create the interface? Did you use QtDesign or write it manually?

**Comment by norimudo** [comment]
I realized that it wasn't the .ui to .py compiler that was the problem, but the way QtCreator opens and then exports your .ui file. Apparently there is a compatibility problem. Where did you create the interface? Did you use QtDesign or write it manually?

**Comment by AIVTDevPKevin** [comment]
> I realized that it wasn't the .ui to .py compiler that was the problem, but the way QtCreator opens and then exports your .ui file. Apparently there is a compatibility problem. Where did you create the interface? Did you use QtDesign or write it manually?

Yeah, I did use QtDesigner for the UI design.
If it's a compatibility problem, you can try using the QtDesigner from my Python environment.
```
AIVTuberSystem_03\Lib\site-packages\qt6_applications\Qt\bin\designer.exe
```

Remember! Don't use the default .ui to .py conversion from QtDesigner.
Use the command I mentioned before.
There are some differences, though I can't exactly tell why. 🫠

**Comment by norimudo** [comment]
Yes, apparently there is a compatibility problem. The designer from your environment works without errors and GUI starts. Thanks you.
